# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- main: cmd/dns-heaven/main.go
  binary: dns-heaven
  goos:
    - darwin
  goarch:
    - amd64
- env:
  - CGO_ENABLED=0

archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
